version: "3"
services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    container_name: gdoc_mongo
    networks:
      - mongo-compose-network
  gdoc1:
    build:
      context: ./gdoc-service
      args:
        PORT: 6000
    environment:
      PORT: 6000
    ports:
      - "6000:6000"
    depends_on:
      - mongodb
    networks:
      - mongo-compose-network
  sharedb1:
    build:
      context: ./sharedb-server
      args:
        PORT: 8080
    environment:
      PORT: 8080
    ports:
      - "8080:8080"
    networks:
      - mongo-compose-network
networks:
  mongo-compose-network:
    driver: bridge
