version: "2.2"
services:
  es01:
    image: elasticsearch:7.8.1
    ports:
      - "9200:9200"
    environment:
      - node.name=es01
      - cluster.name=docker-cluster
      - cluster.initial_master_nodes=es01,es02
      - discovery.seed_hosts=es02
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
    mem_limit: 15073741824
    ulimits:
      memlock:
        soft: -1
        hard: -1
  es02:
    depends_on:
      - es01
    image: elasticsearch:7.8.1
    environment:
      - node.name=es02
      - cluster.name=docker-cluster
      - cluster.initial_master_nodes=es01,es02
      - discovery.seed_hosts=es01
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
    mem_limit: 11073741824
    ulimits:
      memlock:
        soft: -1
        hard: -1