version: "3"
services:
  search0:
    build:
      context: ./search-service
      args:
        PORT: 10100
    environment:
      PORT: 10100
    ports:
      - "10100-10100:10100"
    scale: 1
  indexer1:
    build:
      context: ./search-indexer
      args:
        PORT: 4600
    environment:
      PORT: 4600
    ports:
      - "4600:4600"
  indexer2:
    build:
      context: ./search-indexer
      args:
        PORT: 4601
    environment:
      PORT: 4601
    ports:
      - "4601:4601"
  indexer3:
    build:
      context: ./search-indexer
      args:
        PORT: 4602
    environment:
      PORT: 4602
    ports:
      - "4602:4602"
  indexer4:
    build:
      context: ./search-indexer
      args:
        PORT: 4603
    environment:
      PORT: 4603
    ports:
      - "4603:4603"
  indexer5:
    build:
      context: ./search-indexer
      args:
        PORT: 4604
    environment:
      PORT: 4604
    ports:
      - "4604:4604"
networks:
  mongo-compose-network:
    driver: bridge
