version: "3"
services:
  gdoc1:
    build:
      context: ./gdoc-service
      args:
        PORT: 6000
    environment:
      PORT: 6000
    ports:
      - "6000:6000"
    networks:
      - mongo-compose-network
  sharedb1:
    build:
      context: ./sharedb-server
      args:
        PORT: 8080
    environment:
      PORT: 8080
    ports:
      - "8080:8080"
    networks:
      - mongo-compose-network
  gdoc2:
    build:
      context: ./gdoc-service
      args:
        PORT: 6001
    environment:
      PORT: 6001
    ports:
      - "6001:6001"
    networks:
      - mongo-compose-network
  sharedb2:
    build:
      context: ./sharedb-server
      args:
        PORT: 8081
    environment:
      PORT: 8081
    ports:
      - "8081:8081"
    networks:
      - mongo-compose-network
  gdoc3:
    build:
      context: ./gdoc-service
      args:
        PORT: 6002
    environment:
      PORT: 6002
    ports:
      - "6002:6002"
    networks:
      - mongo-compose-network
  sharedb3:
    build:
      context: ./sharedb-server
      args:
        PORT: 8082
    environment:
      PORT: 8082
    ports:
      - "8082:8082"
    networks:
      - mongo-compose-network
  gdoc4:
    build:
      context: ./gdoc-service
      args:
        PORT: 6003
    environment:
      PORT: 6003
    ports:
      - "6003:6003"
    networks:
      - mongo-compose-network
  sharedb4:
    build:
      context: ./sharedb-server
      args:
        PORT: 8083
    environment:
      PORT: 8083
    ports:
      - "8083:8083"
    networks:
      - mongo-compose-network
  gdoc5:
    build:
      context: ./gdoc-service
      args:
        PORT: 6004
    environment:
      PORT: 6004
    ports:
      - "6004:6004"
    networks:
      - mongo-compose-network
  sharedb5:
    build:
      context: ./sharedb-server
      args:
        PORT: 8084
    environment:
      PORT: 8084
    ports:
      - "8084:8084"
    networks:
      - mongo-compose-network
  gdoc6:
    build:
      context: ./gdoc-service
      args:
        PORT: 6005
    environment:
      PORT: 6005
    ports:
      - "6005:6005"
    networks:
      - mongo-compose-network
  sharedb6:
    build:
      context: ./sharedb-server
      args:
        PORT: 8085
    environment:
      PORT: 8085
    ports:
      - "8085:8085"
    networks:
      - mongo-compose-network
  gdoc7:
    build:
      context: ./gdoc-service
      args:
        PORT: 6006
    environment:
      PORT: 6006
    ports:
      - "6006:6006"
    networks:
      - mongo-compose-network
  sharedb7:
    build:
      context: ./sharedb-server
      args:
        PORT: 8086
    environment:
      PORT: 8086
    ports:
      - "8086:8086"
    networks:
      - mongo-compose-network
  gdoc8:
    build:
      context: ./gdoc-service
      args:
        PORT: 6007
    environment:
      PORT: 6007
    ports:
      - "6007:6007"
    networks:
      - mongo-compose-network
  sharedb8:
    build:
      context: ./sharedb-server
      args:
        PORT: 8087
    environment:
      PORT: 8087
    ports:
      - "8087:8087"
    networks:
      - mongo-compose-network
networks:
  mongo-compose-network:
    driver: bridge
