version: "3"
services:
  gdoc1:
    build:
      context: ./gdoc-service
      args:
        PORT: 6005
    environment:
      PORT: 6005
    ports:
      - "6005:6005"
    networks:
      - mongo-compose-network
  sharedb6:
    build:
      context: ./sharedb-server
      args:
        PORT: 8085
    environment:
      PORT: 8085
    ports:
      - "8085:8085"
    networks:
      - mongo-compose-network
  gdoc2:
    build:
      context: ./gdoc-service
      args:
        PORT: 6006
    environment:
      PORT: 6006
    ports:
      - "6006:6006"
    networks:
      - mongo-compose-network
  sharedb7:
    build:
      context: ./sharedb-server
      args:
        PORT: 8086
    environment:
      PORT: 8086
    ports:
      - "8086:8086"
    networks:
      - mongo-compose-network
  indexer1:
    build:
      context: ./search-indexer
      args:
        PORT: 4601
    environment:
      PORT: 4601
    ports:
      - "4601:4601"
  indexer2:
    build:
      context: ./search-indexer
      args:
        PORT: 4602
    environment:
      PORT: 4602
    ports:
      - "4602:4602"
networks:
  mongo-compose-network:
    driver: bridge
